name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: yc-logging-stream
